#!/bin/sh

set -e

case "$1" in
	purge)
	if find /var/log -maxdepth 1 -name autolog.log -o -name autolog.log.[0-9].gz |
			grep -q var ; then
		echo -n Removing logfiles...
		rm -f /var/log/autolog.log /var/log/autolog.log.[0-9].gz
		echo done.
	fi
	update-rc.d autolog remove >/dev/null
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		;;
esac

#DEBHELPER#

exit 0

